version: '3.8'
services:
  # Container Cơ sở dữ liệu
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always

  # Container Ứng dụng Web
  web-phone:
    build: .
    ports:
      - "8082:80"
    depends_on:
      - db